listen_addresses = '*'
max_connections = 100

shared_buffers = 256MB
work_mem = 16MB

max_wal_size = 1GB
checkpoint_completion_target = 0.9

log_destination = 'stderr'
log_min_duration_statement = 200
log_lock_waits = on
