version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: marquez-db
    environment:
      POSTGRES_DB: marquez
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marquez"]
      interval: 10s
      timeout: 5s
      retries: 5

  marquez-api:
    image: marquezproject/marquez:0.48.0
    container_name: marquez-api
    environment:
      MARQUEZ_DB_HOST: postgres
      MARQUEZ_DB_PORT: 5432
      MARQUEZ_DB_NAME: marquez
      MARQUEZ_DB_USER: marquez
      MARQUEZ_DB_PASSWORD: marquez
    ports:
      - "5555:5000"
      - "5556:5001"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/namespaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  marquez-web:
    image: marquezproject/marquez-web:0.48.0
    container_name: marquez-web
    environment:
      MARQUEZ_HOST: marquez-api
      MARQUEZ_PORT: 5000
    ports:
      - "3000:3000"
    depends_on:
      marquez-api:
        condition: service_healthy

volumes:
  postgres_data:
