version: 2

models:
  - name: fct_orders
    description: Order fact table enriched with customer and product attributes
    config:
      elementary:
        timestamp_column: order_date
    tests:
      - elementary.volume_anomalies:
          timestamp_column: order_date
          sensitivity: 3
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Customer identifier
        tests:
          - not_null
      - name: product_id
        description: Product identifier
        tests:
          - not_null
      - name: order_date
        description: Order timestamp
        tests:
          - not_null
      - name: net_amount
        description: Net order amount
        tests:
          - not_null
          - elementary.column_anomalies:
              column_anomalies:
                - zero_count
                - zero_percent
                - average
      - name: gross_profit
        description: Gross profit per order
        tests:
          - not_null

  - name: dim_customers
    description: Customer dimension with aggregated order metrics
    config:
      elementary:
        timestamp_column: _loaded_at
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: email
        description: Customer email
        tests:
          - unique
          - not_null
      - name: segment
        description: Customer segment
        tests:
          - not_null
      - name: total_orders
        description: Total number of orders
        tests:
          - not_null
      - name: total_revenue
        description: Total customer revenue
        tests:
          - not_null
      - name: value_tier
        description: Customer value classification
        tests:
          - not_null
          - accepted_values:
              values: ['High Value', 'Medium Value', 'Low Value', 'No Orders']
