name: 'elementary_demo'
version: '1.0.0'
config-version: 2

profile: 'elementary_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  elementary_demo:
    +schema: raw

models:
  elementary_demo:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

  elementary:
    +schema: elementary
