version: '3.8'

networks:
  pinot_network:
    driver: bridge

volumes:
  zookeeper_data:
    name: pinot_zookeeper_data
  kafka_data:
    name: pinot_kafka_data
  pinot_controller_data:
    name: pinot_controller_data
  pinot_server_data:
    name: pinot_server_data

services:
  zookeeper:
    image: zookeeper:3.8
    container_name: pinot_zookeeper
    networks:
      - pinot_network
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper_data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: pinot_kafka
    networks:
      - pinot_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pinot-controller:
    image: apachepinot/pinot:1.0.0
    container_name: pinot_controller
    networks:
      - pinot_network
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xms512M -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    command: StartController -zkAddress zookeeper:2181
    volumes:
      - pinot_controller_data:/tmp/pinot-controller
      - ./config:/config
      - ./schemas:/schemas
      - ./table-configs:/table-configs
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pinot-broker:
    image: apachepinot/pinot:1.0.0
    container_name: pinot_broker
    networks:
      - pinot_network
    ports:
      - "8099:8099"
    environment:
      - JAVA_OPTS=-Xms512M -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    command: StartBroker -zkAddress zookeeper:2181
    depends_on:
      pinot-controller:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pinot-server:
    image: apachepinot/pinot:1.0.0
    container_name: pinot_server
    networks:
      - pinot_network
    ports:
      - "8098:8098"
    environment:
      - JAVA_OPTS=-Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    command: StartServer -zkAddress zookeeper:2181
    volumes:
      - pinot_server_data:/tmp/pinot-server
    depends_on:
      pinot-controller:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8098/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped